# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52a7de3b3f65a502cb3032e40799ca9c02f1b963d8a0d5b18561fa28801380a6227b2bd37147af46a06b7fee69a45f46c77436116c866472fba7b389718db5d7

test:
  secret_key_base: 8b26232e5819b5e3d43257723c0e63f4e8856c38bb5500019cc37fe256321021a4084c5cc5d912fe0f1aada2d3838c0edb8c061eace8db9cda519da1e706c2c8

production:
  secret_key_base: ec2766dab9fe2d5fb8a7bfcbb7de7fdf2b729ac2745869be121df867b1ddfd81275052ed7d2b3719bdde4988fbcbc9b3527879be61df598196352ab50efc143e
